# Default message setups, can be overridden in rules.txt per match, do not remove quotes around messages!
warnmsg: '&4[&6PwnFilter&4] &4Warned by PwnFilter!'
kickmsg: '&4[&6PwnFilter&4] &4Kicked by PwnFilter!'
burnmsg: '&4[&6PwnFilter&4] &4Burned by PwnFilter!'
killmsg: '&4[&6PwnFilter&4] &4Killed by PwnFilter!'

# Set the level for MATCH/SEND messages
# Set to 'fine' if you don't want MATCH/SEND events in your main server log
# NOTE: If you have the "then log" action set for a rule, it will log
# at level INFO, regardless of the setting here.
loglevel: info

# Create a PwnFilter.log file in the plugins/PwnFilter directory
# This file will contain all PwnFilter log messages, regardless of level.
logfile: true

# Debug mode (VERY verbose) (Enable logfile above)
debug: false

# Strip color from chat. Permission to bypass pwnfilter.color or pwnfilter.bypass
decolor: true

# Experimental, filter commands as well as chat true/false
commandfilter: true

# Filter text applied to signs
signfilter: true

# Basic spam filter enabled (chat ONLY)
spamfilter: true

# Basic spam filter enabled (commands ONLY)
commandspamfilter: true

# Command White List: Commands to filter, if empty, will filter ALL (except blacklist)
cmdlist: []

# Command Black List: Commands to never filter
cmdblist: 
- tp
- tpa
- warp
- help

# Note: You can also change the priority of event handlers with:
# priority, cmdpriority and signpriority
# Changing priority can allow the event handlers to process messages before or after other
# plugins.



