# Plugin Priority Configuration, options: lowest,low,normal,high,highest
priority: highest

# Default message setups, can be overridden in rules.txt per match, do not remove quotes around messages!
warnmsg: '&4[&6PwnFilter&4] &4Warned by PwnFilter!'
kickmsg: '&4[&6PwnFilter&4] &4Kicked by PwnFilter!'
burnmsg: '&4[&6PwnFilter&4] &4Burned by PwnFilter!'
killmsg: '&4[&6PwnFilter&4] &4Killed by PwnFilter!'

# Logfile Enabling set to true or false
logfile: true

# Strip color from chat. Permission to bypass pwnfilter.color or pwnfilter.bypass
decolor: true

# Experimental, filter commands as well as chat true/false
commandfilter: true

# Command Filter Priority, options: lowest,low,normal,high,highest
cmdpriority: lowest

# Filter text applied to signs
signfilter: true

# Set priority for the onSignChange listener
signpriority: lowest


# Command White List: Commands to filter, if empty, will filter ALL (except blacklist)
cmdlist: []

# Command Black List: Commands to never filter
cmdblist: 
- tp
- tpa
- warp
- help
